# This Docker file is intended for the CI
# A prerequisite is a published application in the .build/release  
FROM mcr.microsoft.com/dotnet/aspnet:3.1

EXPOSE 80
EXPOSE 443

WORKDIR /app
COPY . /app

RUN mkdir -p /app/attachments/images
RUN mkdir -p /app/attachments/attachments
RUN mkdir -p /app/attachments/docs
RUN mkdir -p /app/attachments/personal

ENTRYPOINT ["dotnet", "EAPN.HDVS.Web.dll"]