# This Docker file is intended for the CI
# A prerequisite is a published application in the .build/release  
FROM mcr.microsoft.com/dotnet/aspnet:3.1

EXPOSE 80
EXPOSE 443

WORKDIR /app
COPY . /app
ENTRYPOINT ["dotnet", "EAPN.HDVS.Web.dll"]