version: '3.7'
services:
  hdvs-eapn:
    image: {{image}}
    container_name: hdvs-eapn-{{stage}}
    environment:
      - ConnectionStrings:HDVSDatabase={{{connectionstring}}}
      - AllowedCorsOrigins={{projectdomain}}
      - Authentication:Issuer={{projectdomain}}
      - Authentication:Audience={{projectdomain}}
      - Authentication:SymmetricSecret={{symmetricsecret}}
    restart: unless-stopped
    volumes:
      - type: bind
        source: /container-data/eapn/{{stage}}/attachments
        target: /app/attachments
      - type: bind
        source: /container-data/eapn/{{stage}}/database
        target: /app/database
    networks:
      - hdvs

networks:
  hdvs:
    internal: true
    name: hdvs-{{stage}}-network
