version: '3.7'
services:
  hdvs-eapn:
    image: {{image}}
    container_name: hdvs-eapn-{{stage}}
    environment:
      - ConnectionStrings:HDVSDatabase={{{connectionstring}}}
      - AllowedCorsOrigins={{projectdomain}}
      - Authentication:Issuer={{projectdomain}}
      - Authentication:Audience={{projectdomain}}
      - Authentication:SymmetricSecret={{symmetricsecret}}
    restart: unless-stopped
    networks:
      - hdvs

networks:
  hdvs:
    internal: true
    name: hdvs-{{stage}}-network
