// <auto-generated />
using System;
using EAPN.HDVS.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EAPN.HDVS.Web.Migrations
{
    [DbContext(typeof(HDVSContext))]
    [Migration("20200514071420_Rename roles to permission")]
    partial class Renamerolestopermission
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                ;

            modelBuilder.Entity("EAPN.HDVS.Entities.Asociacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        ;

                    b.Property<bool>("Activa")
                        .HasColumnName("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("Nombre")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Observaciones")
                        .HasColumnName("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Asociaciones","dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Nombre = "EAPN Madrid"
                        });
                });

            modelBuilder.Entity("EAPN.HDVS.Entities.Direccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        ;

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("Descripcion")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("DireccionCompleta")
                        .IsRequired()
                        .HasColumnName("DireccionCompleta")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("PersonaId")
                        .HasColumnName("PersonaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId");

                    b.ToTable("Direcciones","dbo");
                });

            modelBuilder.Entity("EAPN.HDVS.Entities.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        ;

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("Descripcion")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Paises","dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Afganistán"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Alemania"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Andorra"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Angola"
                        },
                        new
                        {
                            Id = 6,
                            Descripcion = "Antigua y Barbuda"
                        },
                        new
                        {
                            Id = 7,
                            Descripcion = "Arabia Saudita"
                        },
                        new
                        {
                            Id = 8,
                            Descripcion = "Argelia"
                        },
                        new
                        {
                            Id = 9,
                            Descripcion = "Argentina"
                        },
                        new
                        {
                            Id = 10,
                            Descripcion = "Armenia"
                        },
                        new
                        {
                            Id = 11,
                            Descripcion = "Australia"
                        },
                        new
                        {
                            Id = 12,
                            Descripcion = "Austria"
                        },
                        new
                        {
                            Id = 13,
                            Descripcion = "Azerbaiyán"
                        },
                        new
                        {
                            Id = 14,
                            Descripcion = "Bahamas"
                        },
                        new
                        {
                            Id = 15,
                            Descripcion = "Bangladés"
                        },
                        new
                        {
                            Id = 16,
                            Descripcion = "Barbados"
                        },
                        new
                        {
                            Id = 17,
                            Descripcion = "Baréin"
                        },
                        new
                        {
                            Id = 18,
                            Descripcion = "Bélgica"
                        },
                        new
                        {
                            Id = 19,
                            Descripcion = "Belice"
                        },
                        new
                        {
                            Id = 20,
                            Descripcion = "Benín"
                        },
                        new
                        {
                            Id = 21,
                            Descripcion = "Bielorrusia"
                        },
                        new
                        {
                            Id = 22,
                            Descripcion = "Birmania"
                        },
                        new
                        {
                            Id = 23,
                            Descripcion = "Bolivia"
                        },
                        new
                        {
                            Id = 24,
                            Descripcion = "Bosnia y Herzegovina"
                        },
                        new
                        {
                            Id = 25,
                            Descripcion = "Botsuana"
                        },
                        new
                        {
                            Id = 26,
                            Descripcion = "Brasil"
                        },
                        new
                        {
                            Id = 27,
                            Descripcion = "Brunéi"
                        },
                        new
                        {
                            Id = 28,
                            Descripcion = "Bulgaria"
                        },
                        new
                        {
                            Id = 29,
                            Descripcion = "Burkina Faso"
                        },
                        new
                        {
                            Id = 30,
                            Descripcion = "Burundi"
                        },
                        new
                        {
                            Id = 31,
                            Descripcion = "Bután"
                        },
                        new
                        {
                            Id = 32,
                            Descripcion = "Cabo Verde"
                        },
                        new
                        {
                            Id = 33,
                            Descripcion = "Camboya"
                        },
                        new
                        {
                            Id = 34,
                            Descripcion = "Camerún"
                        },
                        new
                        {
                            Id = 35,
                            Descripcion = "Canadá"
                        },
                        new
                        {
                            Id = 36,
                            Descripcion = "Catar"
                        },
                        new
                        {
                            Id = 37,
                            Descripcion = "Chad"
                        },
                        new
                        {
                            Id = 38,
                            Descripcion = "Chile"
                        },
                        new
                        {
                            Id = 39,
                            Descripcion = "China"
                        },
                        new
                        {
                            Id = 40,
                            Descripcion = "Chipre"
                        },
                        new
                        {
                            Id = 41,
                            Descripcion = "Ciudad del Vaticano"
                        },
                        new
                        {
                            Id = 42,
                            Descripcion = "Colombia"
                        },
                        new
                        {
                            Id = 43,
                            Descripcion = "Comoras"
                        },
                        new
                        {
                            Id = 44,
                            Descripcion = "Corea del Norte"
                        },
                        new
                        {
                            Id = 45,
                            Descripcion = "Corea del Sur"
                        },
                        new
                        {
                            Id = 46,
                            Descripcion = "Costa de Marfil"
                        },
                        new
                        {
                            Id = 47,
                            Descripcion = "Costa Rica"
                        },
                        new
                        {
                            Id = 48,
                            Descripcion = "Croacia"
                        },
                        new
                        {
                            Id = 49,
                            Descripcion = "Cuba"
                        },
                        new
                        {
                            Id = 50,
                            Descripcion = "Dinamarca"
                        },
                        new
                        {
                            Id = 51,
                            Descripcion = "Dominica"
                        },
                        new
                        {
                            Id = 52,
                            Descripcion = "Ecuador"
                        },
                        new
                        {
                            Id = 53,
                            Descripcion = "Egipto"
                        },
                        new
                        {
                            Id = 54,
                            Descripcion = "El Salvador"
                        },
                        new
                        {
                            Id = 55,
                            Descripcion = "Emiratos Árabes Unidos"
                        },
                        new
                        {
                            Id = 56,
                            Descripcion = "Eritrea"
                        },
                        new
                        {
                            Id = 57,
                            Descripcion = "Eslovaquia"
                        },
                        new
                        {
                            Id = 58,
                            Descripcion = "Eslovenia"
                        },
                        new
                        {
                            Id = 59,
                            Descripcion = "España"
                        },
                        new
                        {
                            Id = 60,
                            Descripcion = "Estados Unidos"
                        },
                        new
                        {
                            Id = 61,
                            Descripcion = "Estonia"
                        },
                        new
                        {
                            Id = 62,
                            Descripcion = "Etiopía"
                        },
                        new
                        {
                            Id = 63,
                            Descripcion = "Filipinas"
                        },
                        new
                        {
                            Id = 64,
                            Descripcion = "Finlandia"
                        },
                        new
                        {
                            Id = 65,
                            Descripcion = "Fiyi"
                        },
                        new
                        {
                            Id = 66,
                            Descripcion = "Francia"
                        },
                        new
                        {
                            Id = 67,
                            Descripcion = "Gabón"
                        },
                        new
                        {
                            Id = 68,
                            Descripcion = "Gambia"
                        },
                        new
                        {
                            Id = 69,
                            Descripcion = "Georgia"
                        },
                        new
                        {
                            Id = 70,
                            Descripcion = "Ghana"
                        },
                        new
                        {
                            Id = 71,
                            Descripcion = "Granada"
                        },
                        new
                        {
                            Id = 72,
                            Descripcion = "Grecia"
                        },
                        new
                        {
                            Id = 73,
                            Descripcion = "Guatemala"
                        },
                        new
                        {
                            Id = 74,
                            Descripcion = "Guyana"
                        },
                        new
                        {
                            Id = 75,
                            Descripcion = "Guinea"
                        },
                        new
                        {
                            Id = 76,
                            Descripcion = "Guinea-Bisáu"
                        },
                        new
                        {
                            Id = 77,
                            Descripcion = "Guinea Ecuatorial"
                        },
                        new
                        {
                            Id = 78,
                            Descripcion = "Haití"
                        },
                        new
                        {
                            Id = 79,
                            Descripcion = "Honduras"
                        },
                        new
                        {
                            Id = 80,
                            Descripcion = "Hungría"
                        },
                        new
                        {
                            Id = 81,
                            Descripcion = "India"
                        },
                        new
                        {
                            Id = 82,
                            Descripcion = "Indonesia"
                        },
                        new
                        {
                            Id = 83,
                            Descripcion = "Irak"
                        },
                        new
                        {
                            Id = 84,
                            Descripcion = "Irán"
                        },
                        new
                        {
                            Id = 85,
                            Descripcion = "Irlanda"
                        },
                        new
                        {
                            Id = 86,
                            Descripcion = "Islandia"
                        },
                        new
                        {
                            Id = 87,
                            Descripcion = "Islas Marshall"
                        },
                        new
                        {
                            Id = 88,
                            Descripcion = "Islas Salomón"
                        },
                        new
                        {
                            Id = 89,
                            Descripcion = "Israel"
                        },
                        new
                        {
                            Id = 90,
                            Descripcion = "Italia"
                        },
                        new
                        {
                            Id = 91,
                            Descripcion = "Jamaica"
                        },
                        new
                        {
                            Id = 92,
                            Descripcion = "Japón"
                        },
                        new
                        {
                            Id = 93,
                            Descripcion = "Jordania"
                        },
                        new
                        {
                            Id = 94,
                            Descripcion = "Kazajistán"
                        },
                        new
                        {
                            Id = 95,
                            Descripcion = "Kenia"
                        },
                        new
                        {
                            Id = 96,
                            Descripcion = "Kirguistán"
                        },
                        new
                        {
                            Id = 97,
                            Descripcion = "Kiribati"
                        },
                        new
                        {
                            Id = 98,
                            Descripcion = "Kuwait"
                        },
                        new
                        {
                            Id = 99,
                            Descripcion = "Laos"
                        },
                        new
                        {
                            Id = 100,
                            Descripcion = "Lesoto"
                        },
                        new
                        {
                            Id = 101,
                            Descripcion = "Letonia"
                        },
                        new
                        {
                            Id = 102,
                            Descripcion = "Líbano"
                        },
                        new
                        {
                            Id = 103,
                            Descripcion = "Liberia"
                        },
                        new
                        {
                            Id = 104,
                            Descripcion = "Libia"
                        },
                        new
                        {
                            Id = 105,
                            Descripcion = "Liechtenstein"
                        },
                        new
                        {
                            Id = 106,
                            Descripcion = "Lituania"
                        },
                        new
                        {
                            Id = 107,
                            Descripcion = "Luxemburgo"
                        },
                        new
                        {
                            Id = 108,
                            Descripcion = "Macedonia del Norte"
                        },
                        new
                        {
                            Id = 109,
                            Descripcion = "Madagascar"
                        },
                        new
                        {
                            Id = 110,
                            Descripcion = "Malasia"
                        },
                        new
                        {
                            Id = 111,
                            Descripcion = "Malaui"
                        },
                        new
                        {
                            Id = 112,
                            Descripcion = "Maldivas"
                        },
                        new
                        {
                            Id = 113,
                            Descripcion = "Malí"
                        },
                        new
                        {
                            Id = 114,
                            Descripcion = "Malta"
                        },
                        new
                        {
                            Id = 115,
                            Descripcion = "Marruecos"
                        },
                        new
                        {
                            Id = 116,
                            Descripcion = "Mauricio"
                        },
                        new
                        {
                            Id = 117,
                            Descripcion = "Mauritania"
                        },
                        new
                        {
                            Id = 118,
                            Descripcion = "México"
                        },
                        new
                        {
                            Id = 119,
                            Descripcion = "Micronesia"
                        },
                        new
                        {
                            Id = 120,
                            Descripcion = "Moldavia"
                        },
                        new
                        {
                            Id = 121,
                            Descripcion = "Mónaco"
                        },
                        new
                        {
                            Id = 122,
                            Descripcion = "Mongolia"
                        },
                        new
                        {
                            Id = 123,
                            Descripcion = "Montenegro"
                        },
                        new
                        {
                            Id = 124,
                            Descripcion = "Mozambique"
                        },
                        new
                        {
                            Id = 125,
                            Descripcion = "Namibia"
                        },
                        new
                        {
                            Id = 126,
                            Descripcion = "Nauru"
                        },
                        new
                        {
                            Id = 127,
                            Descripcion = "Nepal"
                        },
                        new
                        {
                            Id = 128,
                            Descripcion = "Nicaragua"
                        },
                        new
                        {
                            Id = 129,
                            Descripcion = "Níger"
                        },
                        new
                        {
                            Id = 130,
                            Descripcion = "Nigeria"
                        },
                        new
                        {
                            Id = 131,
                            Descripcion = "Noruega"
                        },
                        new
                        {
                            Id = 132,
                            Descripcion = "Nueva Zelanda"
                        },
                        new
                        {
                            Id = 133,
                            Descripcion = "Omán"
                        },
                        new
                        {
                            Id = 134,
                            Descripcion = "Países Bajos"
                        },
                        new
                        {
                            Id = 135,
                            Descripcion = "Pakistán"
                        },
                        new
                        {
                            Id = 136,
                            Descripcion = "Palaos"
                        },
                        new
                        {
                            Id = 137,
                            Descripcion = "Panamá"
                        },
                        new
                        {
                            Id = 138,
                            Descripcion = "Papúa Nueva Guinea"
                        },
                        new
                        {
                            Id = 139,
                            Descripcion = "Paraguay"
                        },
                        new
                        {
                            Id = 140,
                            Descripcion = "Perú"
                        },
                        new
                        {
                            Id = 141,
                            Descripcion = "Polonia"
                        },
                        new
                        {
                            Id = 142,
                            Descripcion = "Portugal"
                        },
                        new
                        {
                            Id = 143,
                            Descripcion = "Reino Unido de Gran Bretaña e Irlanda del Norte"
                        },
                        new
                        {
                            Id = 144,
                            Descripcion = "República Centroafricana"
                        },
                        new
                        {
                            Id = 145,
                            Descripcion = "República Checa"
                        },
                        new
                        {
                            Id = 146,
                            Descripcion = "República del Congo"
                        },
                        new
                        {
                            Id = 147,
                            Descripcion = "República Democrática del Congo"
                        },
                        new
                        {
                            Id = 148,
                            Descripcion = "República Dominicana"
                        },
                        new
                        {
                            Id = 149,
                            Descripcion = "República Sudafricana"
                        },
                        new
                        {
                            Id = 150,
                            Descripcion = "Ruanda"
                        },
                        new
                        {
                            Id = 151,
                            Descripcion = "Rumanía"
                        },
                        new
                        {
                            Id = 152,
                            Descripcion = "Rusia"
                        },
                        new
                        {
                            Id = 153,
                            Descripcion = "Samoa"
                        },
                        new
                        {
                            Id = 154,
                            Descripcion = "San Cristóbal y Nieves"
                        },
                        new
                        {
                            Id = 155,
                            Descripcion = "San Marino"
                        },
                        new
                        {
                            Id = 156,
                            Descripcion = "San Vicente y las Granadinas"
                        },
                        new
                        {
                            Id = 157,
                            Descripcion = "Santa Lucía"
                        },
                        new
                        {
                            Id = 158,
                            Descripcion = "Santo Tomé y Príncipe"
                        },
                        new
                        {
                            Id = 159,
                            Descripcion = "Senegal"
                        },
                        new
                        {
                            Id = 160,
                            Descripcion = "Serbia"
                        },
                        new
                        {
                            Id = 161,
                            Descripcion = "Seychelles"
                        },
                        new
                        {
                            Id = 162,
                            Descripcion = "Sierra Leona"
                        },
                        new
                        {
                            Id = 163,
                            Descripcion = "Singapur"
                        },
                        new
                        {
                            Id = 164,
                            Descripcion = "Siria"
                        },
                        new
                        {
                            Id = 165,
                            Descripcion = "Somalia"
                        },
                        new
                        {
                            Id = 166,
                            Descripcion = "Sri Lanka"
                        },
                        new
                        {
                            Id = 167,
                            Descripcion = "Suazilandia"
                        },
                        new
                        {
                            Id = 168,
                            Descripcion = "Sudán"
                        },
                        new
                        {
                            Id = 169,
                            Descripcion = "Sudán del Sur"
                        },
                        new
                        {
                            Id = 170,
                            Descripcion = "Suecia"
                        },
                        new
                        {
                            Id = 171,
                            Descripcion = "Suiza"
                        },
                        new
                        {
                            Id = 172,
                            Descripcion = "Surinam"
                        },
                        new
                        {
                            Id = 173,
                            Descripcion = "Tailandia"
                        },
                        new
                        {
                            Id = 174,
                            Descripcion = "Tanzania"
                        },
                        new
                        {
                            Id = 175,
                            Descripcion = "Tayikistán"
                        },
                        new
                        {
                            Id = 176,
                            Descripcion = "Timor Oriental"
                        },
                        new
                        {
                            Id = 177,
                            Descripcion = "Togo"
                        },
                        new
                        {
                            Id = 178,
                            Descripcion = "Tonga"
                        },
                        new
                        {
                            Id = 179,
                            Descripcion = "Trinidad y Tobago"
                        },
                        new
                        {
                            Id = 180,
                            Descripcion = "Túnez"
                        },
                        new
                        {
                            Id = 181,
                            Descripcion = "Turkmenistán"
                        },
                        new
                        {
                            Id = 182,
                            Descripcion = "Turquía"
                        },
                        new
                        {
                            Id = 183,
                            Descripcion = "Tuvalu"
                        },
                        new
                        {
                            Id = 184,
                            Descripcion = "Ucrania"
                        },
                        new
                        {
                            Id = 185,
                            Descripcion = "Uganda"
                        },
                        new
                        {
                            Id = 186,
                            Descripcion = "Uruguay"
                        },
                        new
                        {
                            Id = 187,
                            Descripcion = "Uzbekistán"
                        },
                        new
                        {
                            Id = 188,
                            Descripcion = "Vanuatu"
                        },
                        new
                        {
                            Id = 189,
                            Descripcion = "Venezuela"
                        },
                        new
                        {
                            Id = 190,
                            Descripcion = "Vietnam"
                        },
                        new
                        {
                            Id = 191,
                            Descripcion = "Yemen"
                        },
                        new
                        {
                            Id = 192,
                            Descripcion = "Yibuti"
                        },
                        new
                        {
                            Id = 193,
                            Descripcion = "Zambia"
                        },
                        new
                        {
                            Id = 194,
                            Descripcion = "Zimbabue"
                        });
                });

            modelBuilder.Entity("EAPN.HDVS.Entities.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        ;

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("Descripcion")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Perfiles","dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Usuario"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Administrador"
                        });
                });

            modelBuilder.Entity("EAPN.HDVS.Entities.PerfilPermiso", b =>
                {
                    b.Property<int>("PerfilId")
                        .HasColumnName("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("PermisoId")
                        .HasColumnName("PermisoId")
                        .HasColumnType("int");

                    b.HasKey("PerfilId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("PerfilesPermisos","dbo");

                    b.HasData(
                        new
                        {
                            PerfilId = 1,
                            PermisoId = 1
                        },
                        new
                        {
                            PerfilId = 2,
                            PermisoId = 1
                        },
                        new
                        {
                            PerfilId = 2,
                            PermisoId = 2
                        },
                        new
                        {
                            PerfilId = 2,
                            PermisoId = 3
                        },
                        new
                        {
                            PerfilId = 2,
                            PermisoId = 4
                        },
                        new
                        {
                            PerfilId = 2,
                            PermisoId = 5
                        });
                });

            modelBuilder.Entity("EAPN.HDVS.Entities.Permiso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        ;

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnName("Clave")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("Descripcion")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Permisos","dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Clave = "user:login",
                            Descripcion = "Aplicación: Acceder"
                        },
                        new
                        {
                            Id = 2,
                            Clave = "usermng:read",
                            Descripcion = "Usuarios: Lectura"
                        },
                        new
                        {
                            Id = 3,
                            Clave = "usermng:write",
                            Descripcion = "Usuarios: Escritura"
                        },
                        new
                        {
                            Id = 4,
                            Clave = "usermng:delete",
                            Descripcion = "Usuarios: Eliminar"
                        },
                        new
                        {
                            Id = 5,
                            Clave = "usermng:access",
                            Descripcion = "Usuarios: Acceder"
                        },
                        new
                        {
                            Id = 6,
                            Clave = "usermng:admin",
                            Descripcion = "Usuarios: Superadministrador"
                        });
                });

            modelBuilder.Entity("EAPN.HDVS.Entities.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        ;

                    b.Property<string>("Apellido1")
                        .HasColumnName("Apellido1")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Apellido2")
                        .HasColumnName("Apellido2")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnName("Codigo")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("DNI")
                        .HasColumnName("DNI")
                        .HasColumnType("nvarchar(12)")
                        .HasMaxLength(12);

                    b.Property<bool>("DocumentacionEmpadronamiento")
                        .HasColumnName("DocumentacionEmpadronamiento")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnName("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("NacionalidadId")
                        .HasColumnName("NacionalidadId1")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnName("Nombre")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("SexoId")
                        .HasColumnName("NacionalidadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NacionalidadId");

                    b.HasIndex("SexoId");

                    b.ToTable("Personas","dbo");
                });

            modelBuilder.Entity("EAPN.HDVS.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        ;

                    b.Property<DateTime>("FinValidez")
                        .HasColumnName("FinValidez")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnName("Token")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<int>("UsuarioId")
                        .HasColumnName("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("RefreshTokens","dbo");
                });

            modelBuilder.Entity("EAPN.HDVS.Entities.Sexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        ;

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnName("Descripcion")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Sexos","dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Hombre"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Mujer"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Otros"
                        });
                });

            modelBuilder.Entity("EAPN.HDVS.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("int")
                        ;

                    b.Property<bool>("Activo")
                        .HasColumnName("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .HasColumnName("Apellidos")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("AsociacionId")
                        .HasColumnName("AsociacionId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnName("Email")
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<DateTime?>("FinBloqueo")
                        .HasColumnName("FinBloqueo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnName("Hash")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<int>("IntentosLogin")
                        .HasColumnName("IntentosLogin")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnName("Nombre")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Observaciones")
                        .HasColumnName("Observaciones")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnName("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AsociacionId");

                    b.ToTable("Usuarios","dbo");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apellidos = "Rodríguez Gallego",
                            AsociacionId = 0,
                            Email = "Jjavierrg@gmail.com",
                            Hash = "$2b$12$sn1hzFuoYJwKxocoCsn3me4gLtEeMG9sJrz/FQQu6XMww3bdoSgOe",
                            IntentosLogin = 0,
                            Nombre = "José Javier"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Apellidos = "Test",
                            AsociacionId = 0,
                            Email = "test@test.com",
                            Hash = "$2b$12$vrDFckbZnoXbB9oFeLqqn.UQtnQ2UdYOJC/r6UqrjLfS00LagnO0q",
                            IntentosLogin = 0,
                            Nombre = "Test"
                        });
                });

            modelBuilder.Entity("EAPN.HDVS.Entities.UsuarioPerfil", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnName("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("PerfilId")
                        .HasColumnName("PerfilId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "PerfilId");

                    b.HasIndex("PerfilId");

                    b.ToTable("UsuariosPerfiles","dbo");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            PerfilId = 2
                        },
                        new
                        {
                            UsuarioId = 2,
                            PerfilId = 1
                        });
                });

            modelBuilder.Entity("EAPN.HDVS.Entities.UsuarioPermiso", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnName("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("PermisoId")
                        .HasColumnName("PermisoId")
                        .HasColumnType("int");

                    b.HasKey("UsuarioId", "PermisoId");

                    b.HasIndex("PermisoId");

                    b.ToTable("UsuariosPermisos","dbo");

                    b.HasData(
                        new
                        {
                            UsuarioId = 1,
                            PermisoId = 6
                        });
                });

            modelBuilder.Entity("EAPN.HDVS.Entities.Direccion", b =>
                {
                    b.HasOne("EAPN.HDVS.Entities.Persona", "Persona")
                        .WithMany("Direcciones")
                        .HasForeignKey("PersonaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EAPN.HDVS.Entities.PerfilPermiso", b =>
                {
                    b.HasOne("EAPN.HDVS.Entities.Perfil", "Perfil")
                        .WithMany("Permisos")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EAPN.HDVS.Entities.Permiso", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EAPN.HDVS.Entities.Persona", b =>
                {
                    b.HasOne("EAPN.HDVS.Entities.Pais", "Nacionalidad")
                        .WithMany()
                        .HasForeignKey("NacionalidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EAPN.HDVS.Entities.Sexo", "Sexo")
                        .WithMany()
                        .HasForeignKey("SexoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EAPN.HDVS.Entities.RefreshToken", b =>
                {
                    b.HasOne("EAPN.HDVS.Entities.Usuario", "Usuario")
                        .WithMany("Tokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EAPN.HDVS.Entities.Usuario", b =>
                {
                    b.HasOne("EAPN.HDVS.Entities.Asociacion", "Asociacion")
                        .WithMany()
                        .HasForeignKey("AsociacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EAPN.HDVS.Entities.UsuarioPerfil", b =>
                {
                    b.HasOne("EAPN.HDVS.Entities.Perfil", "Perfil")
                        .WithMany("Usuarios")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EAPN.HDVS.Entities.Usuario", "Usuario")
                        .WithMany("Perfiles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EAPN.HDVS.Entities.UsuarioPermiso", b =>
                {
                    b.HasOne("EAPN.HDVS.Entities.Permiso", "Permiso")
                        .WithMany()
                        .HasForeignKey("PermisoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EAPN.HDVS.Entities.Usuario", "Usuario")
                        .WithMany("PermisosAdicionales")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
