name: Deploy to dev environment

on:
  push:
    branches:
      - develop

env:
  ACTION_ENVIRONMENT: dev

jobs:
  build:
    uses: ./.github/workflows/build-artefact.yml
    with:
      ACTION_ENVIRONMENT: ${{ env.ACTION_ENVIRONMENT }}
    secrets: inherit

  upload-docker:
    needs: build
    uses: ./.github/workflows/dockerhub.yml
    with:
      ACTION_ENVIRONMENT: ${{ env.ACTION_ENVIRONMENT }}
    secrets: inherit

  deploy-portainer:
    needs: upload-docker
    uses: ./.github/workflows/portainer.yml
    with:
      ACTION_ENVIRONMENT: ${{ env.ACTION_ENVIRONMENT }}
    secrets: inherit
