name: Upload to DockerHub

on:
  workflow_call:
    inputs:
      ACTION_ENVIRONMENT:
        required: true
        type: string

jobs:
  generate-docker-image:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    environment: ${{ inputs.ACTION_ENVIRONMENT }}
    steps:
      - name: 📝 Set env vars
        run: |
          echo "TAG_VERSION=$(date +'%Y%m%d.%H%M')" >> $GITHUB_ENV
          echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
          echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: 📥 Checkout dockerfile-CI
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Dockerfile-CI

      - name: 📁 Create app directory and move Dockerfile-CI
        run: |
          mkdir -p ./app
          mv Dockerfile-CI ./app/Dockerfile

      - name: 📥 Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ vars.ENV_TAG }}-${{ github.sha }}
          path: ./app

      - name: 🐳 Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🐳 Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./app
          file: ./app/Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.GIT_SHA }}
            ${{ env.IMAGE_NAME }}:${{ env.TAG_VERSION }}
            ${{ env.IMAGE_NAME }}:${{ vars.DOCKER_TAG }}
